apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-import
data:
  realm-jad-dev.json: |
    {
      "realm": "jad-dev",
      "enabled": true,
      "displayName": "JAD Dev Realm",
      "sslRequired": "none",
      "registrationAllowed": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "components": {
        "org.keycloak.userprofile.UserProfileProvider": [
          {
            "name": "declarative-user-profile",
            "providerId": "declarative-user-profile",
            "subComponents": {},
            "config": {
              "kc.user.profile.config": [
                "{\"unmanagedAttributePolicy\":\"ADMIN_EDIT\",\"attributes\":[{\"name\":\"username\",\"displayName\":\"${username}\",\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\",\"user\"]},\"validations\":{\"length\":{\"min\":3,\"max\":255},\"username-prohibited-characters\":{},\"up-username-not-idn-homograph\":{}},\"multivalued\":false},{\"name\":\"email\",\"displayName\":\"${email}\",\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\",\"user\"]},\"validations\":{\"email\":{},\"length\":{\"max\":255}},\"multivalued\":false},{\"name\":\"firstName\",\"displayName\":\"${firstName}\",\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\",\"user\"]},\"validations\":{\"length\":{\"max\":255},\"person-name-prohibited-characters\":{}},\"multivalued\":false},{\"name\":\"lastName\",\"displayName\":\"${lastName}\",\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\",\"user\"]},\"validations\":{\"length\":{\"max\":255},\"person-name-prohibited-characters\":{}},\"multivalued\":false},{\"name\":\"participant_context_id\",\"displayName\":\"Participant Context ID\",\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\"]},\"validations\":{\"length\":{\"max\":255}},\"multivalued\":false},{\"name\":\"operator_id\",\"displayName\":\"Operator ID\",\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\"]},\"validations\":{\"length\":{\"max\":255}},\"multivalued\":false},{\"name\":\"edc_connector_config\",\"displayName\":\"EDC Connector Config\",\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\"]},\"validations\":{\"length\":{\"max\":20000}},\"multivalued\":false}]}"
              ]
            }
          }
        ]
      },
      "roles": {
        "realm": [
          {
            "name": "operator"
          },
          {
            "name": "participant"
          }
        ]
      },
      "clients": [
        {
          "clientId": "jad-ui",
          "name": "JAD UI",
          "enabled": true,
          "publicClient": true,
          "protocol": "openid-connect",
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "frontchannelLogout": true,
          "attributes": {
            "pkce.code.challenge.method": "S256"
          },
          "redirectUris": [
            "http://localhost:4200/login",
            "http://localhost:4200/*",
            "http://jad.localhost/*"
          ],
          "webOrigins": [
            "http://localhost:4200",
            "http://jad.localhost"
          ],
          "defaultClientScopes": [
            "profile",
            "email",
            "roles"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ],
          "protocolMappers": [
            {
              "name": "participant-context-id",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-attribute-mapper",
              "consentRequired": false,
              "config": {
                "user.attribute": "participant_context_id",
                "claim.name": "participant_context_id",
                "jsonType.label": "String",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            },
            {
              "name": "operator-id",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-attribute-mapper",
              "consentRequired": false,
              "config": {
                "user.attribute": "operator_id",
                "claim.name": "operator_id",
                "jsonType.label": "String",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            },
            {
              "name": "edc-connector-config",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-attribute-mapper",
              "consentRequired": false,
              "config": {
                "user.attribute": "edc_connector_config",
                "claim.name": "edc_connector_config",
                "jsonType.label": "String",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            }
          ]
        }
      ],
      "users": [
        {
          "username": "operator",
          "enabled": true,
          "emailVerified": true,
          "firstName": "JAD",
          "lastName": "Operator",
          "email": "operator@jad.local",
          "attributes": {
            "operator_id": [
              "operator-dev-01"
            ]
          },
          "credentials": [
            {
              "type": "password",
              "value": "operator",
              "temporary": false
            }
          ],
          "realmRoles": [
            "operator"
          ]
        },
        {
          "username": "participant",
          "enabled": true,
          "emailVerified": true,
          "firstName": "JAD",
          "lastName": "Participant",
          "email": "participant@jad.local",
          "attributes": {
            "participant_context_id": [
              "participant-context-dev-01"
            ],
            "edc_connector_config": [
              "{\"connectorName\":\"demo-provider\",\"managementUrl\":\"http://jad.localhost/api/management\",\"managementApiVersion\":\"v5beta/participants/participant-context-dev-01\",\"defaultUrl\":\"http://jad.localhost/api/management/health\",\"protocolUrl\":\"http://jad.localhost/api/dsp/participant-context-dev-01/http-dsp-profile-2025-1\",\"protocolVersion\":\"dataspace-protocol-http:2025-1\",\"did\":\"did:web:identity.jad.localhost:demo-provider\",\"authorization\":{\"key\":\"Authorization\",\"value\":\"Bearer replace-me\"}}"
            ]
          },
          "credentials": [
            {
              "type": "password",
              "value": "participant",
              "temporary": false
            }
          ],
          "realmRoles": [
            "participant"
          ]
        }
      ]
    }
