apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edc-v
resources:
  - secret-keycloak-admin.yaml
  - deployment.yaml
configMapGenerator:
  - name: keycloakagent-config
    files:
      - agent.py
      - requirements.txt
    options:
      labels:
        app: keycloakagent
generatorOptions:
  disableNameSuffixHash: true
