apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edc-v
resources:
  - secret-admin.yaml
  - configmap-realm.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - httproute.yaml
